name: pull-request
on: [push, pull_request]

jobs:
  linting:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Lint
        uses: github/super-linter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_BASH: true
          VALIDATE_YAML: true
          VALIDATE_TERRAFORM: true
